### ISSUE TITLE
how to employ the grow_mol2/mut_mol2 function

### ISSUE THREAD

**Issue by MachineGUN001** [DrrDom/crem#25]
hi, DrrDom,

could you please provide some example for using `grow_mol2` and `mut_mol2` functions?
In particular, how to set the parameters, such as `replace_ids `? 
Many many thanks

**Comment by DrrDom** [comment]
I do not fully understand the question. These functions can be used if one wants to process several molecules simultaneously. This could be efficient with a relatively small number of parallel processes, otherwise access to a fragment DB will become a bottleneck.
All arguments can be supplied as usual. Example

```python
from crem.crem import mutate_mol, mutate_mol2
from multiprocessing import Pool
from functools import partial
from rdkit import Chem

m = Chem.MolFromSmiles('CCCC')

pool = Pool(3)

for res in pool.imap_unordered(partial(mutate_mol2, db_name='replacements_sa2.db', replace_ids=[0]), [m]):
    print(len(res), res)
```

**Comment by MachineGUN001** [comment]
got it.  thank you for providing the demonstration and explanation. This is a very interesting use.
